  apiVersion: storage.cnrm.cloud.google.com/v1beta1
  kind: StorageBucket
  metadata:
    annotations:
      cnrm.cloud.google.com/force-destroy: "false"
    # StorageBucket names must be globally unique. Replace ${PROJECT_ID?} with your project ID.
    name: customer-a-bucket-test
  spec:
    lifecycleRule:
      - action:
          type: Delete
        condition:
          age: 7
    versioning:
      enabled: false
    uniformBucketLevelAccess: true
