apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: customer-a
resources:
- namespace.yaml
- gcp-bucket.yaml

helmCharts:
  - name: podinfo
    repo: https://stefanprodan.github.io/podinfo
    namespace: customer-a
    valuesInline:
      service:
        type: LoadBalancer

