apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gcp-bucket.yaml

helmCharts:
  - name: podinfo
    repo: https://stefanprodan.github.io/podinfo
    namespace: customer-a
    valuesInline:
      service:
        type: LoadBalancer

